http://localhost:3001/info

###

http://localhost:3001/api/persons/64d689f781e89ffddfd8f8c0

###

http://localhost:3001/api/persons/8


###

http://localhost:3001/api/persons


###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Testi Henkilö",
    "number": "044 123 4567"
}

###

DELETE http://localhost:3001/api/persons/64d68c8a95a8a05db2b8206b